"""updatePOTableWithIECdepTypeFK

Revision ID: 72d550e34c45
Revises: c2b5404b05d6
Create Date: 2022-07-03 07:41:17.402080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d550e34c45'
down_revision = 'c2b5404b05d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_request', sa.Column('description', sa.String(), nullable=False))
    op.add_column('procurement_request', sa.Column('justification', sa.String(), nullable=False))
    op.add_column('procurement_request', sa.Column('oracle_id', sa.Integer(), nullable=False))
    op.add_column('procurement_request', sa.Column('iec_dep_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('procurement_request_iec_id_fkey', 'procurement_request', type_='foreignkey')
    op.create_foreign_key(None, 'procurement_request', 'iec_dep_type', ['iec_dep_type_id'], ['id'])
    op.drop_column('procurement_request', 'iec_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procurement_request', sa.Column('iec_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'procurement_request', type_='foreignkey')
    op.create_foreign_key('procurement_request_iec_id_fkey', 'procurement_request', 'iec', ['iec_id'], ['id'])
    op.drop_column('procurement_request', 'iec_dep_type_id')
    op.drop_column('procurement_request', 'oracle_id')
    op.drop_column('procurement_request', 'justification')
    op.drop_column('procurement_request', 'description')
    # ### end Alembic commands ###
