"""addAttachmentNameToIECTable

Revision ID: bd0d57261582
Revises: cd5231eeb2fa
Create Date: 2022-07-03 12:24:03.692518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0d57261582'
down_revision = 'cd5231eeb2fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iec', sa.Column('attachment_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iec', 'attachment_name')
    # ### end Alembic commands ###
