"""addMimeTypeToIecTable

Revision ID: cd5231eeb2fa
Revises: 72d550e34c45
Create Date: 2022-07-03 11:39:57.070622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5231eeb2fa'
down_revision = '72d550e34c45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iec', sa.Column('attachment_mimetype', sa.Text(), nullable=True))
    op.add_column('procurement_request', sa.Column('iec_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'procurement_request', 'iec', ['iec_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procurement_request', type_='foreignkey')
    op.drop_column('procurement_request', 'iec_id')
    op.drop_column('iec', 'attachment_mimetype')
    # ### end Alembic commands ###
